package main

import (
	"encoding/json"
	"fmt"
	"os"
)

type AutoGenerated []struct {
	GlobalID int `json:"global_id"`
}

func main() {
	file, err := os.Open("data-20190514T0100.json")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	var data AutoGenerated
	decoder := json.NewDecoder(file)
	if err := decoder.Decode(&data); err != nil {
		panic(err)
	}
	sum := 0
	for _, item := range data {
		sum += item.GlobalID
	}
	fmt.Println(sum)
}
